### PR TITLE
Update pkgs

### PR DESCRIPTION
**Pull request by freaknils**
Hi, please add bareos and icinga to your Build System

### CODE REVIEW

**Comment by unixfox** [comment]
I removed your requested packages because I got the same error as you here: https://github.com/asdil12/aurbs/issues/25
That's a recurrent error that I get for a lot's of others packages. I planning to switch to another software when I have the time.

**Comment by freaknils** [comment]
Ok very sad. I thougth you are using a better software than aurbs. I also tested aurbot but it has some trouble too. If you find a realy good alternative please tell me :-)

Thanks!

**Comment by unixfox** [comment]
I came across multiple softwares that use Travis for building AUR packages, that's interesting because I will not need to pay a server anymore but that requires more lot's of work because Travis has some limitation.
If you want to look at it, here is the list:
- https://github.com/mikkeloscar/arch-travis
- https://github.com/Denton-L/aur-autobuild-template
- https://github.com/lirios/archbuild
- https://github.com/Edenhofer/abs/blob/master/aurpublish
- https://blog.bastelfreak.de/2016/05/creating-a-reliable-arch-linux-package-build-environment/
- https://github.com/virtapi/arch-package-builder

**Comment by aylen384** [comment]
Should be fixed with aurbs version 2.0.0
You might get a missing dependeny error listed in the webui until you run `aurbs` for the 2nd time after you freshly added the pkg.
After the 1st run of aurbs the provides and splitpkgs are in the local database and the dependencies can be found.

**Pull request merged**
